In [33]:
import pandas as p 

raw_data0 = p.read_csv('E0.csv',header="infer")
raw_data1 = p.read_csv('E1.csv',header="infer")
raw_data2 = p.read_csv('E2.csv',header="infer")
raw_data3 = p.read_csv('E3.csv',header="infer")
raw_data4 = p.read_csv('E4.csv',header="infer")



def parse_data(data):
    try:
        new_data = data[['Date','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'HTHG', 'HTAG', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF']]
        return new_data
    except:
        print("Error")
        
new_data0 = parse_data(raw_data0)
new_data0

,Date,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF
0,09/08/2019,Liverpool,Norwich,4,1,4,0,15,12,7,5,9,9
1,10/08/2019,West Ham,Man City,0,5,0,1,5,14,3,9,6,13
2,10/08/2019,Bournemouth,Sheffield United,1,1,0,0,13,8,3,3,10,19
3,10/08/2019,Burnley,Southampton,3,0,0,0,10,11,4,3,6,12
4,10/08/2019,Crystal Palace,Everton,0,0,0,0,6,10,2,3,16,14
5,10/08/2019,Watford,Brighton,0,3,0,1,11,5,3,3,15,11
6,10/08/2019,Tottenham,Aston Villa,3,1,0,1,31,7,7,4,13,9
7,11/08/2019,Leicester,Wolves,0,0,0,0,15,8,1,2,3,13
8,11/08/2019,Newcastle,Arsenal,0,1,0,0,9,8,2,2,12,7
9,11/08/2019,Man United,Chelsea,4,0,1,0,11,18,5,7,15,13
10,17/08/2019,Arsenal,Burnley,2,1,1,1,16,18,9,5,13,11
11,17/08/2019,Aston Villa,Bournemouth,1,2,0,2,22,12,7,4,10,13
12,17/08/2019,Brighton,West Ham,1,1,0,0,16,8,4,3,11,10
13,17/08/2019,Everton,Watford,1,0,1,0,12,8,2,2,11,11
14,17/08/2019,Norwich,Newcastle,3,1,1,0,15,10,8,3,9,11
15,17/08/2019,Southampton,Liverpool,1,2,0,1,14,15,3,6,10,6
16,17/08/2019,Man City,Tottenham,2,2,2,1,30,3,10,2,14,4
17,18/08/2019,Sheffield United,Crystal Palace,1,0,0,0,15,6,3,4,16,11
18,18/08/2019,Chelsea,Leicester,1,1,1,0,14,12,5,3,9,14
19,19/08/2019,Wolves,Man United,1,1,0,1,6,9,2,2,17,8
20,23/08/2019,Aston Villa,Everton,2,0,1,0,7,12,3,1,10,18
21,24/08/2019,Norwich,Chelsea,2,3,2,2,6,23,5,8,9,9
22,24/08/2019,Brighton,Southampton,0,2,0,0,12,12,3,4,9,10
23,24/08/2019,Man United,Crystal Palace,1,2,0,1,22,5,3,3,8,18
24,24/08/2019,Sheffield United,Leicester,1,2,0,1,8,10,3,2,11,6
25,24/08/2019,Watford,West Ham,1,3,1,1,23,16,3,10,12,11
26,24/08/2019,Liverpool,Arsenal,3,1,1,0,25,9,5,3,8,5
27,25/08/2019,Bournemouth,Man City,1,3,1,2,10,19,7,5,7,13
28,25/08/2019,Tottenham,Newcastle,0,1,0,1,17,8,2,3,10,5
29,25/08/2019,Wolves,Burnley,1,1,0,1,17,13,2,4,9,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,02/11/2019,Bournemouth,Man United,1,0,1,0,12,15,6,4,14,12
101,02/11/2019,Arsenal,Wolves,1,1,1,0,10,25,4,8,6,15
102,02/11/2019,Aston Villa,Liverpool,1,2,1,0,5,25,2,6,12,9
103,02/11/2019,Brighton,Norwich,2,0,0,0,21,7,5,0,11,8
104,02/11/2019,Man City,Southampton,2,1,0,1,26,3,4,3,11,10
105,02/11/2019,Sheffield United,Burnley,3,0,3,0,13,6,6,0,8,12
106,02/11/2019,West Ham,Newcastle,2,3,0,2,16,12,6,9,10,7
107,02/11/2019,Watford,Chelsea,1,2,0,1,12,16,3,10,8,5
108,03/11/2019,Crystal Palace,Leicester,0,2,0,0,12,14,3,5,15,16
109,03/11/2019,Everton,Tottenham,1,1,0,0,7,4,3,2,9,8
110,08/11/2019,Norwich,Watford,0,2,0,1,17,12,5,2,7,13
111,09/11/2019,Chelsea,Crystal Palace,2,0,0,0,23,3,5,1,9,17
112,09/11/2019,Burnley,West Ham,3,0,2,0,14,7,12,4,17,10
113,09/11/2019,Newcastle,Bournemouth,2,1,1,1,20,16,9,3,10,5
114,09/11/2019,Southampton,Everton,1,2,0,1,4,24,3,5,12,12
115,09/11/2019,Tottenham,Sheffield United,1,1,0,0,17,14,5,4,6,9
116,09/11/2019,Leicester,Arsenal,2,0,0,0,19,8,7,1,10,10
117,10/11/2019,Man United,Brighton,3,1,2,0,21,6,11,2,10,14
118,10/11/2019,Wolves,Aston Villa,2,1,1,0,17,13,5,4,17,8
119,10/11/2019,Liverpool,Man City,3,1,2,0,12,18,5,3,10,5
120,23/11/2019,West Ham,Tottenham,2,3,0,2,11,15,4,6,12,14
121,23/11/2019,Arsenal,Southampton,2,2,1,1,12,21,5,6,13,19
122,23/11/2019,Bournemouth,Wolves,1,2,0,2,9,17,2,7,10,12
123,23/11/2019,Brighton,Leicester,0,2,0,0,7,19,0,9,9,1
124,23/11/2019,Crystal Palace,Liverpool,1,2,0,0,16,12,6,4,8,7
125,23/11/2019,Everton,Norwich,0,2,0,0,18,13,7,5,12,11
126,23/11/2019,Watford,Burnley,0,3,0,0,15,11,4,5,14,13
127,23/11/2019,Man City,Chelsea,2,1,2,1,15,11,4,2,5,9
128,24/11/2019,Sheffield United,Man United,3,3,1,0,12,11,8,5,13,10
129,25/11/2019,Aston Villa,Newcastle,2,0,2,0,17,11,8,5,10,9

In [29]:
new_data1 = parse_data(raw_data1)
new_data1

,Date,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF
0,10/8/18,Man United,Leicester,2,1,1,0,8,13,6,4,11,8
1,11/8/18,Bournemouth,Cardiff,2,0,1,0,12,10,4,1,11,9
2,11/8/18,Fulham,Crystal Palace,0,2,0,1,15,10,6,9,9,11
3,11/8/18,Huddersfield,Chelsea,0,3,0,2,6,13,1,4,9,8
4,11/8/18,Newcastle,Tottenham,1,2,1,2,15,15,2,5,11,12
5,11/8/18,Watford,Brighton,2,0,1,0,19,6,5,0,10,16
6,11/8/18,Wolves,Everton,2,2,1,1,11,6,4,5,8,7
7,12/8/18,Arsenal,Man City,0,2,0,1,9,17,3,8,11,14
8,12/8/18,Liverpool,West Ham,4,0,2,0,18,5,8,2,14,9
9,12/8/18,Southampton,Burnley,0,0,0,0,18,16,3,6,10,9
10,18/08/2018,Cardiff,Newcastle,0,0,0,0,12,12,1,6,14,16
11,18/08/2018,Chelsea,Arsenal,3,2,2,2,24,15,11,6,12,9
12,18/08/2018,Everton,Southampton,2,1,2,0,13,15,7,4,8,20
13,18/08/2018,Leicester,Wolves,2,0,2,0,6,11,2,3,10,8
14,18/08/2018,Tottenham,Fulham,3,1,1,0,25,10,11,3,9,5
15,18/08/2018,West Ham,Bournemouth,1,2,1,0,11,12,5,5,14,10
16,19/08/2018,Brighton,Man United,3,2,3,1,6,9,3,3,16,13
17,19/08/2018,Burnley,Watford,1,3,1,1,8,9,3,6,8,19
18,19/08/2018,Man City,Huddersfield,6,1,3,1,32,5,14,1,9,4
19,20/08/2018,Crystal Palace,Liverpool,0,2,0,1,8,16,2,6,6,13
20,25/08/2018,Arsenal,West Ham,3,1,1,1,17,13,10,5,16,13
21,25/08/2018,Bournemouth,Everton,2,2,0,0,17,11,5,3,12,10
22,25/08/2018,Huddersfield,Cardiff,0,0,0,0,5,14,1,4,8,10
23,25/08/2018,Liverpool,Brighton,1,0,1,0,22,6,8,2,8,14
24,25/08/2018,Southampton,Leicester,1,2,0,0,11,8,5,5,13,11
25,25/08/2018,Wolves,Man City,1,1,0,0,11,18,2,6,13,8
26,26/08/2018,Fulham,Burnley,4,2,3,2,25,12,12,2,11,8
27,26/08/2018,Newcastle,Chelsea,1,2,0,0,6,15,2,3,16,8
28,26/08/2018,Watford,Crystal Palace,2,1,0,0,13,9,5,3,14,11
29,27/08/2018,Man United,Tottenham,0,3,0,0,23,9,5,5,11,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,26/04/2019,Liverpool,Huddersfield,5,0,3,0,21,5,7,1,5,14
351,27/04/2019,Brighton,Newcastle,1,1,0,1,9,9,2,1,7,10
352,27/04/2019,Crystal Palace,Everton,0,0,0,0,8,22,0,3,9,15
353,27/04/2019,Fulham,Cardiff,1,0,0,0,8,13,2,8,10,8
354,27/04/2019,Southampton,Bournemouth,3,3,1,2,22,9,7,5,8,9
355,27/04/2019,Tottenham,West Ham,0,1,0,0,14,16,4,7,3,8
356,27/04/2019,Watford,Wolves,1,2,0,1,10,11,1,4,10,11
357,28/04/2019,Burnley,Man City,0,1,0,0,2,25,0,7,5,7
358,28/04/2019,Leicester,Arsenal,3,0,0,0,24,6,12,1,13,13
359,28/04/2019,Man United,Chelsea,1,1,1,1,7,16,5,3,9,14
360,3/5/19,Everton,Burnley,2,0,2,0,20,5,6,1,8,9
361,4/5/19,Bournemouth,Tottenham,1,0,0,0,20,11,6,5,11,12
362,4/5/19,Cardiff,Crystal Palace,2,3,1,2,18,21,8,7,14,11
363,4/5/19,Newcastle,Liverpool,2,3,1,2,14,11,7,4,10,4
364,4/5/19,West Ham,Southampton,3,0,1,0,17,11,6,1,2,11
365,4/5/19,Wolves,Fulham,1,0,0,0,19,6,6,2,10,15
366,5/5/19,Arsenal,Brighton,1,1,1,0,20,11,8,5,9,14
367,5/5/19,Chelsea,Watford,3,0,0,0,19,15,9,3,6,12
368,5/5/19,Huddersfield,Man United,1,1,0,1,7,23,3,7,10,10
369,6/5/19,Man City,Leicester,1,0,0,0,19,7,5,2,12,5
370,12/5/19,Brighton,Man City,1,4,1,2,6,20,2,9,12,8
371,12/5/19,Burnley,Arsenal,1,3,0,0,14,17,5,6,11,3
372,12/5/19,Crystal Palace,Bournemouth,5,3,3,1,17,16,8,8,11,8
373,12/5/19,Fulham,Newcastle,0,4,0,2,16,13,2,6,6,8
374,12/5/19,Leicester,Chelsea,0,0,0,0,9,14,3,4,9,8
375,12/5/19,Liverpool,Wolves,2,0,1,0,13,7,5,2,3,11
376,12/5/19,Man United,Cardiff,0,2,0,1,26,13,10,4,9,6
377,12/5/19,Southampton,Huddersfield,1,1,1,0,10,10,3,3,8,6
378,12/5/19,Tottenham,Everton,2,2,1,0,11,17,3,9,10,13
379,12/5/19,Watford,West Ham,1,4,0,2,17,16,8,9,10,10

In [30]:
new_data2 = parse_data(raw_data2)
new_data2

,Date,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF
0,11/8/17,Arsenal,Leicester,4,3,2,2,27,6,10,3,9,12
1,12/8/17,Brighton,Man City,0,2,0,0,6,14,2,4,6,9
2,12/8/17,Chelsea,Burnley,2,3,0,3,19,10,6,5,16,11
3,12/8/17,Crystal Palace,Huddersfield,0,3,0,2,14,8,4,6,7,19
4,12/8/17,Everton,Stoke,1,0,1,0,9,9,4,1,13,10
5,12/8/17,Southampton,Swansea,0,0,0,0,29,4,2,0,10,13
6,12/8/17,Watford,Liverpool,3,3,2,1,9,14,4,5,14,8
7,12/8/17,West Brom,Bournemouth,1,0,1,0,16,9,6,2,15,3
8,13/08/2017,Man United,West Ham,4,0,1,0,22,9,6,1,19,7
9,13/08/2017,Newcastle,Tottenham,0,2,0,0,6,18,3,6,6,10
10,19/08/2017,Bournemouth,Watford,0,2,0,0,6,19,2,7,6,14
11,19/08/2017,Burnley,West Brom,0,1,0,0,20,8,0,1,11,11
12,19/08/2017,Leicester,Brighton,2,0,1,0,14,5,4,2,8,10
13,19/08/2017,Liverpool,Crystal Palace,1,0,0,0,23,4,13,1,12,13
14,19/08/2017,Southampton,West Ham,3,2,2,1,14,16,5,8,18,10
15,19/08/2017,Stoke,Arsenal,1,0,0,0,11,18,4,6,6,11
16,19/08/2017,Swansea,Man United,0,4,0,1,6,17,1,8,12,11
17,20/08/2017,Huddersfield,Newcastle,1,0,0,0,7,13,3,5,13,10
18,20/08/2017,Tottenham,Chelsea,1,2,0,1,18,9,6,2,14,21
19,21/08/2017,Man City,Everton,1,1,0,1,19,7,6,2,7,9
20,26/08/2017,Bournemouth,Man City,1,2,1,1,9,19,3,8,13,14
21,26/08/2017,Crystal Palace,Swansea,0,2,0,1,16,7,3,3,9,6
22,26/08/2017,Huddersfield,Southampton,0,0,0,0,16,6,6,3,10,10
23,26/08/2017,Man United,Leicester,2,0,0,0,22,11,7,4,8,7
24,26/08/2017,Newcastle,West Ham,3,0,1,0,16,8,8,3,17,11
25,26/08/2017,Watford,Brighton,0,0,0,0,8,16,0,2,7,18
26,27/08/2017,Chelsea,Everton,2,0,2,0,18,7,7,0,12,7
27,27/08/2017,Liverpool,Arsenal,4,0,2,0,18,8,10,0,6,9
28,27/08/2017,Tottenham,Burnley,1,1,0,0,28,13,5,3,9,9
29,27/08/2017,West Brom,Stoke,1,1,0,0,10,16,2,2,10,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,28/04/2018,Swansea,Chelsea,0,1,0,1,10,11,3,3,13,9
351,29/04/2018,Man United,Arsenal,2,1,1,0,17,8,3,3,12,7
352,29/04/2018,West Ham,Man City,1,4,1,2,4,19,1,7,5,11
353,30/04/2018,Tottenham,Watford,2,0,1,0,13,13,3,5,11,10
354,4/5/18,Brighton,Man United,1,0,0,0,11,16,4,3,5,3
355,5/5/18,Bournemouth,Swansea,1,0,1,0,13,12,5,3,10,10
356,5/5/18,Everton,Southampton,1,1,0,0,9,11,3,5,14,12
357,5/5/18,Leicester,West Ham,0,2,0,1,13,13,2,3,8,9
358,5/5/18,Stoke,Crystal Palace,1,2,1,0,7,13,2,2,18,12
359,5/5/18,Watford,Newcastle,2,1,2,0,11,9,8,1,9,11
360,5/5/18,West Brom,Tottenham,1,0,0,0,9,18,1,5,13,12
361,6/5/18,Arsenal,Burnley,5,0,2,0,16,6,8,2,6,7
362,6/5/18,Chelsea,Liverpool,1,0,1,0,12,10,4,5,12,9
363,6/5/18,Man City,Huddersfield,0,0,0,0,15,5,2,3,9,4
364,8/5/18,Swansea,Southampton,0,1,0,0,11,13,3,8,7,15
365,9/5/18,Chelsea,Huddersfield,1,1,0,0,22,3,5,2,7,10
366,9/5/18,Leicester,Arsenal,3,1,1,0,19,14,10,7,7,12
367,9/5/18,Man City,Brighton,3,1,2,1,19,6,7,3,5,7
368,9/5/18,Tottenham,Newcastle,1,0,0,0,11,14,7,3,10,8
369,10/5/18,West Ham,Man United,0,0,0,0,9,16,2,6,12,12
370,13/05/2018,Burnley,Bournemouth,1,2,1,0,12,16,4,5,14,9
371,13/05/2018,Crystal Palace,West Brom,2,0,0,0,11,7,5,1,10,11
372,13/05/2018,Huddersfield,Arsenal,0,1,0,1,18,9,3,4,11,7
373,13/05/2018,Liverpool,Brighton,4,0,2,0,22,2,11,1,3,6
374,13/05/2018,Man United,Watford,1,0,1,0,7,7,1,3,6,11
375,13/05/2018,Newcastle,Chelsea,3,0,1,0,16,6,6,2,11,10
376,13/05/2018,Southampton,Man City,0,1,0,0,8,13,3,2,8,10
377,13/05/2018,Swansea,Stoke,1,2,1,2,26,8,11,5,12,9
378,13/05/2018,Tottenham,Leicester,5,4,1,2,14,16,6,9,9,13
379,13/05/2018,West Ham,Everton,3,1,1,0,15,14,4,7,10,13

In [31]:
new_data3 = parse_data(raw_data3)
new_data3

,Date,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF
0,13/08/16,Burnley,Swansea,0,1,0,0,10,17,3,9,10,14
1,13/08/16,Crystal Palace,West Brom,0,1,0,0,14,13,4,3,12,15
2,13/08/16,Everton,Tottenham,1,1,1,0,12,13,6,4,10,14
3,13/08/16,Hull,Leicester,2,1,1,0,14,18,5,5,8,17
4,13/08/16,Man City,Sunderland,2,1,1,0,16,7,4,3,11,14
5,13/08/16,Middlesbrough,Stoke,1,1,1,0,12,12,2,1,18,14
6,13/08/16,Southampton,Watford,1,1,0,1,24,5,6,1,8,12
7,14/08/16,Arsenal,Liverpool,3,4,1,1,9,16,5,7,13,17
8,14/08/16,Bournemouth,Man United,1,3,0,1,9,11,3,7,7,10
9,15/08/16,Chelsea,West Ham,2,1,0,0,16,7,6,3,16,16
10,19/08/16,Man United,Southampton,2,0,1,0,12,13,5,1,11,8
11,20/08/16,Burnley,Liverpool,2,0,2,0,3,26,2,5,14,5
12,20/08/16,Leicester,Arsenal,0,0,0,0,8,13,1,4,11,7
13,20/08/16,Stoke,Man City,1,4,0,2,8,12,3,6,12,13
14,20/08/16,Swansea,Hull,0,2,0,0,13,12,3,4,7,10
15,20/08/16,Tottenham,Crystal Palace,1,0,0,0,20,10,5,2,19,9
16,20/08/16,Watford,Chelsea,1,2,0,0,6,13,2,4,20,10
17,20/08/16,West Brom,Everton,1,2,1,1,11,13,4,7,16,10
18,21/08/16,Sunderland,Middlesbrough,1,2,0,2,18,8,5,3,11,14
19,21/08/16,West Ham,Bournemouth,1,0,0,0,15,8,2,5,15,15
20,27/08/16,Chelsea,Burnley,3,0,2,0,22,6,10,0,6,9
21,27/08/16,Crystal Palace,Bournemouth,1,1,0,1,24,10,5,3,15,10
22,27/08/16,Everton,Stoke,1,0,0,0,21,8,9,1,14,11
23,27/08/16,Hull,Man United,0,1,0,0,8,29,2,9,9,6
24,27/08/16,Leicester,Swansea,2,1,1,0,13,9,6,3,14,10
25,27/08/16,Southampton,Sunderland,1,1,0,0,16,5,7,2,15,8
26,27/08/16,Tottenham,Liverpool,1,1,0,1,11,13,4,3,11,17
27,27/08/16,Watford,Arsenal,1,3,0,3,14,10,6,7,18,15
28,28/08/16,Man City,West Ham,3,1,2,0,22,9,5,2,5,10
29,28/08/16,West Brom,Middlesbrough,0,0,0,0,13,7,2,2,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,6/5/17,Swansea,Everton,1,0,1,0,9,8,4,2,5,13
351,7/5/17,Arsenal,Man United,2,0,0,0,9,10,4,4,14,10
352,7/5/17,Liverpool,Southampton,0,0,0,0,17,4,8,0,9,4
353,8/5/17,Chelsea,Middlesbrough,3,0,2,0,21,2,7,1,8,21
354,10/5/17,Southampton,Arsenal,0,2,0,0,14,11,3,4,5,5
355,12/5/17,Everton,Watford,1,0,0,0,15,14,6,2,7,11
356,12/5/17,West Brom,Chelsea,0,1,0,0,7,24,2,5,13,8
357,13/05/17,Bournemouth,Burnley,2,1,1,0,18,14,6,3,6,11
358,13/05/17,Man City,Leicester,2,1,2,1,17,9,5,4,12,16
359,13/05/17,Middlesbrough,Southampton,1,2,0,1,14,14,3,4,19,11
360,13/05/17,Stoke,Arsenal,1,4,0,1,10,10,4,6,13,7
361,13/05/17,Sunderland,Swansea,0,2,0,2,13,3,4,3,13,6
362,14/05/17,Crystal Palace,Hull,4,0,2,0,12,9,4,0,13,14
363,14/05/17,Tottenham,Man United,2,1,1,0,14,8,7,2,14,15
364,14/05/17,West Ham,Liverpool,0,4,0,1,10,26,3,11,5,10
365,15/05/17,Chelsea,Watford,4,3,2,1,24,9,9,3,7,12
366,16/05/17,Arsenal,Sunderland,2,0,0,0,36,6,13,2,15,10
367,16/05/17,Man City,West Brom,3,1,2,0,21,5,10,2,8,11
368,17/05/17,Southampton,Man United,0,0,0,0,17,11,6,1,7,10
369,18/05/17,Leicester,Tottenham,1,6,0,2,12,26,5,12,11,8
370,21/05/17,Arsenal,Everton,3,1,2,0,17,22,9,7,10,15
371,21/05/17,Burnley,West Ham,1,2,1,1,9,14,1,4,11,14
372,21/05/17,Chelsea,Sunderland,5,1,1,1,28,7,8,3,8,15
373,21/05/17,Hull,Tottenham,1,7,0,3,10,19,4,14,14,5
374,21/05/17,Leicester,Bournemouth,1,1,0,1,21,10,5,4,11,10
375,21/05/17,Liverpool,Middlesbrough,3,0,1,0,25,9,10,3,13,8
376,21/05/17,Man United,Crystal Palace,2,0,2,0,9,6,2,1,16,10
377,21/05/17,Southampton,Stoke,0,1,0,0,14,14,6,3,12,10
378,21/05/17,Swansea,West Brom,2,1,0,1,12,16,2,5,8,10
379,21/05/17,Watford,Man City,0,5,0,4,6,15,3,9,12,10

In [32]:
new_data4 = parse_data(raw_data4)
new_data4

,Date,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF
0,8/8/15,Bournemouth,Aston Villa,0,1,0,0,11,7,2,3,13,13
1,8/8/15,Chelsea,Swansea,2,2,2,1,11,18,3,10,15,16
2,8/8/15,Everton,Watford,2,2,0,1,10,11,5,5,7,13
3,8/8/15,Leicester,Sunderland,4,2,3,0,19,10,8,5,13,17
4,8/8/15,Man United,Tottenham,1,0,1,0,9,9,1,4,12,12
5,8/8/15,Norwich,Crystal Palace,1,3,0,1,17,11,6,7,14,20
6,9/8/15,Arsenal,West Ham,0,2,0,1,22,8,6,4,12,9
7,9/8/15,Newcastle,Southampton,2,2,1,1,9,15,4,5,9,12
8,9/8/15,Stoke,Liverpool,0,1,0,0,7,8,1,3,9,16
9,10/8/15,West Brom,Man City,0,3,0,2,9,19,2,7,12,9
10,14/08/15,Aston Villa,Man United,0,1,0,1,5,9,1,2,14,10
11,15/08/15,Southampton,Everton,0,3,0,2,17,10,4,4,11,10
12,15/08/15,Sunderland,Norwich,1,3,0,2,6,19,2,6,7,7
13,15/08/15,Swansea,Newcastle,2,0,1,0,19,4,6,2,11,8
14,15/08/15,Tottenham,Stoke,2,2,2,0,13,16,7,7,15,11
15,15/08/15,Watford,West Brom,0,0,0,0,16,6,5,0,13,10
16,15/08/15,West Ham,Leicester,1,2,0,2,10,11,3,6,11,12
17,16/08/15,Crystal Palace,Arsenal,1,2,1,1,11,20,4,7,14,12
18,16/08/15,Man City,Chelsea,3,0,1,0,18,10,8,3,19,13
19,17/08/15,Liverpool,Bournemouth,1,0,1,0,18,13,2,2,11,18
20,22/08/15,Crystal Palace,Aston Villa,2,1,0,0,16,11,6,2,12,15
21,22/08/15,Leicester,Tottenham,1,1,0,0,13,19,2,6,7,14
22,22/08/15,Man United,Newcastle,0,0,0,0,20,7,8,0,15,11
23,22/08/15,Norwich,Stoke,1,1,1,1,21,6,7,1,16,5
24,22/08/15,Sunderland,Swansea,1,1,0,1,10,20,2,9,16,9
25,22/08/15,West Ham,Bournemouth,3,4,0,2,10,15,4,7,8,11
26,23/08/15,Everton,Man City,0,2,0,0,10,16,1,9,5,7
27,23/08/15,Watford,Southampton,0,0,0,0,13,14,0,5,10,11
28,23/08/15,West Brom,Chelsea,2,3,1,3,15,15,6,5,9,12
29,24/08/15,Arsenal,Liverpool,0,0,0,0,19,15,5,8,2,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,30/04/16,Watford,Aston Villa,3,2,1,1,18,7,6,2,14,10
351,30/04/16,West Brom,West Ham,0,3,0,2,15,8,5,4,14,7
352,1/5/16,Man United,Leicester,1,1,1,1,21,14,6,3,16,10
353,1/5/16,Southampton,Man City,4,2,2,1,14,6,7,5,12,9
354,1/5/16,Swansea,Liverpool,3,1,2,0,18,11,9,3,12,13
355,2/5/16,Chelsea,Tottenham,2,2,0,2,13,16,5,5,9,20
356,7/5/16,Aston Villa,Newcastle,0,0,0,0,2,9,0,3,8,13
357,7/5/16,Bournemouth,West Brom,1,1,0,1,12,12,4,4,5,8
358,7/5/16,Crystal Palace,Stoke,2,1,0,1,17,12,4,3,8,18
359,7/5/16,Leicester,Everton,3,1,2,0,32,9,8,5,4,12
360,7/5/16,Norwich,Man United,0,1,0,0,8,15,2,2,11,10
361,7/5/16,Sunderland,Chelsea,3,2,1,2,15,9,4,8,11,9
362,7/5/16,West Ham,Swansea,1,4,0,2,25,13,7,6,11,8
363,8/5/16,Liverpool,Watford,2,0,1,0,19,14,5,3,10,15
364,8/5/16,Man City,Arsenal,2,2,1,1,14,5,3,2,16,10
365,8/5/16,Tottenham,Southampton,1,2,1,1,20,10,6,2,8,16
366,10/5/16,West Ham,Man United,3,2,1,0,20,3,6,2,6,18
367,11/5/16,Liverpool,Chelsea,1,1,0,1,28,13,9,7,11,12
368,11/5/16,Norwich,Watford,4,2,3,1,18,12,6,7,8,12
369,11/5/16,Sunderland,Everton,3,0,2,0,14,17,8,6,15,7
370,15/05/16,Arsenal,Aston Villa,4,0,1,0,16,5,7,2,12,6
371,15/05/16,Chelsea,Leicester,1,1,0,0,17,18,4,5,4,12
372,15/05/16,Everton,Norwich,3,0,2,0,15,10,8,2,7,11
373,15/05/16,Newcastle,Tottenham,5,1,2,0,19,17,10,5,7,6
374,15/05/16,Southampton,Crystal Palace,4,1,1,0,18,16,5,4,7,14
375,15/05/16,Stoke,West Ham,2,1,0,1,7,20,4,7,8,12
376,15/05/16,Swansea,Man City,1,1,1,1,4,18,1,5,4,19
377,15/05/16,Watford,Sunderland,2,2,0,1,21,6,6,4,11,10
378,15/05/16,West Brom,Liverpool,1,1,1,1,13,7,1,3,11,14
379,17/05/16,Man United,Bournemouth,3,1,1,0,12,7,5,0,9,8

In [35]:
final = p.concat([new_data0, new_data1, new_data2, new_data3, new_data4], axis=0)
print(len(final))

1650